project:
  type: website
  output-dir: docs
  
website:
  title: "Kayla's Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Digital Marketing Analytics"
        href: digital-marketing.qmd
      - text: "Marketing Analytics Projects"
        href: marketing-analytics.qmd
      - text: "Resume"
        href: resume.qmd
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    include-in-header:
      text: |
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-GXF3VQHDR6"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-GXF3VQHDR6');
        </script>